# title: Code Smells for Machine Learning Applications
title: DSLinter - Linter for Machine Learning - Specific Code Smells
baseURL: https://hynn01.github.io/dslinter/
languageCode: en-us
theme: "PaperMod"
paginate: 50

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - identifier: CodeSmells
      name: Code Smells
      url: posts/codesmells/
      weight: 1
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 2
    - name: Search
      url: search/
      weight: 3
    # - identifier: Survey
    #   name: Survey
    #   url: ""
    #   weight: 4

outputs:
  home:
      - HTML
      - RSS
      - JSON # is necessary
      
taxonomies:
    # CodeSmell: CodeSmell
    tag: tags
    # series: series

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: DSLinter - Linter for Machine Learning Application - Specific Code Smells
  description: ""
  # keywords: [Blog, Portfolio, PaperMod]
  # author: Me
  # author: ["Me", "You"] # multiple authors
  defaultTheme: light # dark, light
  disableThemeToggle: false

  # ShowReadingTime: true
  # ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "DSLinter - Linter for Machine Learning - Specific Code Smells"
    # text: Code Smells for Machine Learning Applications

  # # profile-mode
  # profileMode:
  #   enabled: false # needs to be explicitly set
  #   title: ExampleSite
  #   subtitle: "This is subtitle"
  #   imageUrl: "<img location>"
  #   imageWidth: 120
  #   imageHeight: 120
  #   imageTitle: my image
  #   buttons:
  #     # - name: Posts
  #     #   url: posts
  #     # - name: Tags
  #     #   url: tags

  # home-info mode
  homeInfoParams:
    Title: "DSLinter - Linter for Machine Learning - Specific Code Smells"
    Content: |

      - `dslinter` is a pylint plugin for linting data science and machine learning code. We plan to support the following Python libraries: TensorFlow, PyTorch, Scikit-Learn, Pandas, NumPy and SciPy.
      > 
      - `dslinter` aims to help data scientists and developers produce and maintain high-quality machine learning application code. 
      >
      - `dslinter` does this by checking violations of best coding practices for machine learning libraries.
      >
      &#128295 To install from source for development purposes: clone this repo and install the plugin with: `pip install -e .`
      >
      &#128295 To install from the Python Package Index: `pip install dslinter`
      >
      &#128526 To only use the checkers implemented in this plugin, run: `pylint --load-plugins=dslinter --disable=all --enable=dataframe,nan,hyperparameters,import,data-leakage,controlling-randomness,excessive-hyperparameter-precision,pca-scaler <other_options> <path_to_sources>`
      >
      &#128526 To expand a current pylint configuration with the checkers from this plugin, run: `pylint --load-plugins=dslinter <other_options> <path_to_sources>`
      >
      &#128221 Tests can be run by using the pytest package: `pytest .`

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
